# Generated by Django 6.0.3 on 2026-05-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_sparepart_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم البنك'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='SDG', max_length=10, verbose_name='العملة'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('bank', 'تحويل بنكي')], default='cash', max_length=10, verbose_name='طريقة الدفع'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الإشعار'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sender_account_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم حساب المرسل'),
        ),
    ]
