# Generated by Django 6.0.3 on 2026-05-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_invoice_bank_name_invoice_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='الهاتف')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
            ],
            options={
                'verbose_name': 'رسالة تواصل',
                'verbose_name_plural': 'رسائل التواصل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=100, verbose_name='اسم المنصة')),
                ('value', models.CharField(max_length=255, verbose_name='القيمة (رقم/رابط)')),
                ('icon_name', models.CharField(max_length=100, verbose_name='اسم الأيقونة (Lucide)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'وسيلة اتصال',
                'verbose_name_plural': 'وسائل الاتصال',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='محل قطع الغيار', max_length=255, verbose_name='اسم الموقع')),
                ('logo', models.CharField(blank=True, default='', max_length=500, verbose_name='رابط الشعار')),
                ('hero_title', models.CharField(default='أفضل قطع الغيار لسيارتك', max_length=255, verbose_name='عنوان الهيرو')),
                ('hero_subtitle', models.TextField(default='نوفر أفضل قطع الغيار الأصلية والمضمونة لكافة أنواع السيارات بأسعار منافسة.', verbose_name='العنوان الفرعي للهيرو')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
        migrations.AddField(
            model_name='sparepart',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='منتج مميز'),
        ),
    ]
