# Generated by Django 6.0.3 on 2026-05-29 05:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customer_storeresource_invoice_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='اسم الشركة')),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='الشخص المسؤول')),
                ('phone_number', models.CharField(max_length=50, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'مورد',
                'verbose_name_plural': 'الموردون',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='SupplyDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_added', models.PositiveIntegerField(verbose_name='الكمية المضافة')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سعر الشراء (التكلفة)')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='التكلفة الإجمالية')),
                ('date_received', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاستلام')),
                ('invoice_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='الرقم المرجعي للفاتورة')),
            ],
            options={
                'verbose_name': 'عملية توريد',
                'verbose_name_plural': 'عمليات التوريد',
                'ordering': ['-date_received'],
            },
        ),
        migrations.DeleteModel(
            name='StoreResource',
        ),
        migrations.AddField(
            model_name='sparepart',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_parts', to='api.supplier', verbose_name='المورد'),
        ),
        migrations.AddField(
            model_name='supplydeal',
            name='spare_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='api.sparepart', verbose_name='قطعة الغيار'),
        ),
        migrations.AddField(
            model_name='supplydeal',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='api.supplier', verbose_name='المورد'),
        ),
    ]
