# Generated by Django 6.0.3 on 2026-05-29 12:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_supplier_supplydeal_delete_storeresource_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='اسم الزبون')),
                ('phone_number', models.CharField(max_length=50, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'تم التأكيد'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='القيمة الإجمالية')),
            ],
            options={
                'verbose_name': 'طلب خارجي',
                'verbose_name_plural': 'طلبات خارجية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سعر الوحدة')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.publicorder', verbose_name='الطلب')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='public_order_items', to='api.sparepart', verbose_name='قطعة الغيار')),
            ],
            options={
                'verbose_name': 'عنصر طلب خارجي',
                'verbose_name_plural': 'عناصر طلبات خارجية',
            },
        ),
    ]
