# Generated by Django 6.0.3 on 2026-05-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_publicorder_publicorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicorder',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان / المنطقة'),
        ),
    ]
