# Generated by Django 6.0.3 on 2026-05-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_publicorder_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500, verbose_name='محتوى التنبيه')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التنبيه')),
                ('notification_type', models.CharField(choices=[('ORDER', 'طلب شراء'), ('MESSAGE', 'رسالة تواصل')], max_length=20, verbose_name='نوع التنبيه')),
            ],
            options={
                'verbose_name': 'تنبيه',
                'verbose_name_plural': 'تنبيهات',
                'ordering': ['-created_at'],
            },
        ),
    ]
