# Generated by Django 5.2.17 on 2026-09-15 20:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_sitesetting_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='تكلفة الوحدة وقت البيع'),
        ),
        migrations.AlterField(
            model_name='publicorderitem',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spare_parts', to='api.category', verbose_name='الفئة'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.IntegerField(help_text='موجب للزيادة وسالب للنقصان.', verbose_name='التغيير')),
                ('quantity_after', models.PositiveIntegerField(verbose_name='الكمية بعد الحركة')),
                ('reason', models.CharField(choices=[('sale', 'بيع'), ('public_order_confirmed', 'تأكيد طلب خارجي'), ('public_order_cancelled', 'إلغاء طلب خارجي'), ('restock', 'توريد'), ('return', 'مرتجع'), ('adjustment', 'تسوية يدوية')], max_length=32, verbose_name='السبب')),
                ('reference', models.CharField(blank=True, default='', max_length=100, verbose_name='المرجع')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='تكلفة الوحدة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='api.sparepart', verbose_name='قطعة الغيار')),
            ],
            options={
                'verbose_name': 'حركة مخزون',
                'verbose_name_plural': 'حركات المخزون',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['spare_part', '-created_at'], name='api_stockmo_spare_p_3fd624_idx'), models.Index(fields=['reason'], name='api_stockmo_reason_1957d5_idx')],
            },
        ),
    ]
