# Generated by Django 5.2.17 on 2026-09-20 12:05

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_invoiceitem_cost_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_models/', validators=[api.validators.validate_image_upload], verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', validators=[api.validators.validate_image_upload], verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', validators=[api.validators.validate_image_upload], verbose_name='الشعار'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='parts/', validators=[api.validators.validate_image_upload], verbose_name='الصورة'),
        ),
    ]
