# Generated by Django 5.2.17 on 2026-09-23 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_carmodel_image_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicorderitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='تكلفة الوحدة وقت الطلب'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='spare_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='api.sparepart', verbose_name='قطعة الغيار'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='api_notific_is_read_9d379e_idx'),
        ),
        migrations.AddIndex(
            model_name='publicorder',
            index=models.Index(fields=['status'], name='api_publico_status_ab424a_idx'),
        ),
        migrations.AddIndex(
            model_name='sparepart',
            index=models.Index(fields=['is_featured'], name='api_sparepa_is_feat_0359d4_idx'),
        ),
    ]
