# Generated by Django 5.2.17 on 2026-10-07 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_publicorderitem_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='idempotency_key',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, verbose_name='مفتاح إعادة المحاولة'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='request_fingerprint',
            field=models.CharField(blank=True, default='', editable=False, max_length=64, verbose_name='بصمة الطلب'),
        ),
        migrations.AddField(
            model_name='supplydeal',
            name='previous_purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True, verbose_name='متوسط التكلفة قبل التوريد'),
        ),
        migrations.AddField(
            model_name='supplydeal',
            name='restock_movement',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supply_deal', to='api.stockmovement', verbose_name='حركة الإضافة'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('sale', 'بيع'), ('public_order_confirmed', 'تأكيد طلب خارجي'), ('public_order_cancelled', 'إلغاء طلب خارجي'), ('restock', 'توريد'), ('restock_reversal', 'إلغاء توريد'), ('return', 'مرتجع'), ('adjustment', 'تسوية يدوية')], max_length=32, verbose_name='السبب'),
        ),
        migrations.AlterField(
            model_name='supplydeal',
            name='spare_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='api.sparepart', verbose_name='قطعة الغيار'),
        ),
        migrations.AlterField(
            model_name='supplydeal',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='api.supplier', verbose_name='المورد'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('cashier', 'idempotency_key'), name='unique_invoice_idempotency_key_per_cashier'),
        ),
    ]
