# Generated by Django 5.2.17 on 2026-10-07 06:53

import api.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_invoice_idempotency_supply_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الحساب / البنك')),
                ('account_number', models.CharField(blank=True, default='', max_length=100, verbose_name='رقم الحساب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'حساب بنكي',
                'verbose_name_plural': 'الحسابات البنكية',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='markup_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='هامش الربح %'),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حد الائتمان'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('retail', 'مستهلك'), ('workshop', 'ورشة'), ('wholesale', 'تاجر جملة')], default='retail', max_length=20, verbose_name='نوع العميل'),
        ),
        migrations.AddField(
            model_name='customer',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='نسبة الخصم %'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المبلغ الآجل'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المدفوع عند البيع'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='business_address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='عنوان المحل'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='business_phone',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='هاتف المحل'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='default_markup_percent',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='هامش الربح الافتراضي %'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='price_rounding',
            field=models.PositiveIntegerField(default=0, help_text='تقريب سعر البيع لأعلى إلى أقرب مضاعف لهذا الرقم (0 = بلا تقريب).', verbose_name='تقريب الأسعار'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='receipt_footer',
            field=models.CharField(blank=True, default='شكراً لتعاملكم معنا', max_length=255, verbose_name='تذييل الإيصال'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='receipt_paper',
            field=models.CharField(choices=[('80mm', 'إيصال حراري 80 مم'), ('58mm', 'إيصال حراري 58 مم'), ('a4', 'ورق A4')], default='80mm', max_length=10, verbose_name='مقاس الإيصال'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='tax_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='الرقم الضريبي'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='wholesale_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='خصم الجملة %'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='workshop_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='خصم الورش %'),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='aliases',
            field=models.TextField(blank=True, default='', help_text='التسميات الدارجة للقطعة، كل اسم في سطر أو مفصولة بفواصل.', verbose_name='أسماء أخرى'),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='barcode',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='الباركود'),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='العلامة / المصنّع'),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='cost_currency',
            field=models.CharField(blank=True, default='', help_text='فارغة = عملة المؤسسة (لا تسعير بسعر الصرف).', max_length=3, verbose_name='عملة الشراء'),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='foreign_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='تكلفة الشراء بعملة الشراء'),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='markup_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='فارغ = هامش الفئة ثم هامش المؤسسة.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='هامش الربح %'),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='oem_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='الرقم الأصلي (OEM)'),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='price_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر تحديث للسعر'),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='quality_grade',
            field=models.CharField(blank=True, choices=[('original', 'أصلي'), ('commercial', 'تجاري'), ('used', 'مستعمل')], default='', max_length=20, verbose_name='درجة الجودة'),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='search_text',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='supplydeal',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='عملة الشراء'),
        ),
        migrations.AddField(
            model_name='supplydeal',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='سعر الصرف'),
        ),
        migrations.AddField(
            model_name='supplydeal',
            name='foreign_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='التكلفة بعملة الشراء'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='api.customer', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('bank', 'تحويل بنكي'), ('mixed', 'مختلط'), ('credit', 'آجل')], default='cash', max_length=10, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('sale', 'بيع'), ('public_order_confirmed', 'تأكيد طلب خارجي'), ('public_order_cancelled', 'إلغاء طلب خارجي'), ('restock', 'توريد'), ('restock_reversal', 'إلغاء توريد'), ('return', 'مرتجع'), ('adjustment', 'تسوية يدوية'), ('opening', 'رصيد افتتاحي'), ('stock_count', 'جرد')], max_length=32, verbose_name='السبب'),
        ),
        migrations.CreateModel(
            name='DailyClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='اليوم')),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='نقد بداية اليوم')),
                ('expected_cash', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='النقد المتوقع')),
                ('counted_cash', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='النقد المعدود')),
                ('difference', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='الفرق')),
                ('summary', models.JSONField(default=dict, verbose_name='ملخص اليوم')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_closes', to=settings.AUTH_USER_MODEL, verbose_name='أقفلها')),
            ],
            options={
                'verbose_name': 'إقفال يومية',
                'verbose_name_plural': 'إقفالات اليومية',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('category', models.CharField(max_length=100, verbose_name='البند')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ')),
                ('method', models.CharField(choices=[('cash', 'نقدي'), ('bank', 'تحويل بنكي')], default='cash', max_length=10, verbose_name='الطريقة')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='api.bankaccount', verbose_name='الحساب البنكي')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصروفات',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_method', models.CharField(choices=[('cash', 'نقدي'), ('bank', 'تحويل بنكي'), ('account', 'خصم من حساب العميل')], max_length=10, verbose_name='طريقة ردّ المبلغ')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='قيمة المرتجع')),
                ('reason', models.CharField(blank=True, default='', max_length=255, verbose_name='السبب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_returns', to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='api.invoice', verbose_name='الفاتورة')),
            ],
            options={
                'verbose_name': 'مرتجع بيع',
                'verbose_name_plural': 'مرتجعات البيع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر الوحدة')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='تكلفة الوحدة')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المجموع')),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='api.invoiceitem', verbose_name='بند الفاتورة')),
                ('sale_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.salereturn', verbose_name='المرتجع')),
            ],
            options={
                'verbose_name': 'بند مرتجع',
                'verbose_name_plural': 'بنود المرتجعات',
            },
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='العنوان')),
                ('status', models.CharField(choices=[('draft', 'قيد العدّ'), ('applied', 'مطبّق'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applied_stock_counts', to=settings.AUTH_USER_MODEL, verbose_name='طبّقه')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
            ],
            options={
                'verbose_name': 'جرد',
                'verbose_name_plural': 'عمليات الجرد',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3, verbose_name='العملة')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_rates', to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
            ],
            options={
                'verbose_name': 'سعر صرف',
                'verbose_name_plural': 'أسعار الصرف',
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['currency', '-created_at'], name='api_exchang_currenc_1c1b50_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('sale', 'دفعة بيع'), ('collection', 'تحصيل دين'), ('refund', 'ردّ مبلغ مرتجع')], max_length=20, verbose_name='النوع')),
                ('method', models.CharField(choices=[('cash', 'نقدي'), ('bank', 'تحويل بنكي')], max_length=10, verbose_name='الطريقة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ')),
                ('bank_name', models.CharField(blank=True, default='', max_length=255, verbose_name='البنك')),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الإشعار')),
                ('reference_key', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('sender_account_number', models.CharField(blank=True, default='', max_length=100, verbose_name='رقم حساب المرسل')),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='payment_proofs/', validators=[api.validators.validate_image_upload], verbose_name='صورة الإشعار')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المطابقة')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='api.bankaccount', verbose_name='الحساب البنكي')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='api.customer', verbose_name='العميل')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='api.invoice', verbose_name='الفاتورة')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL, verbose_name='طابقها')),
                ('sale_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='api.salereturn', verbose_name='المرتجع')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'المدفوعات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='api_payment_created_c18666_idx'), models.Index(fields=['method', 'kind'], name='api_payment_method_fa6021_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('reference_key__isnull', False)), fields=('reference_key',), name='unique_payment_transfer_reference')],
            },
        ),
        migrations.CreateModel(
            name='StockCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counted_quantity', models.PositiveIntegerField(verbose_name='الكمية المعدودة')),
                ('system_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='رصيد النظام')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='count_lines', to='api.sparepart', verbose_name='القطعة')),
                ('stock_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='api.stockcount', verbose_name='الجرد')),
            ],
            options={
                'verbose_name': 'سطر جرد',
                'verbose_name_plural': 'أسطر الجرد',
                'constraints': [models.UniqueConstraint(fields=('stock_count', 'spare_part'), name='unique_part_per_stock_count')],
            },
        ),
    ]
