# Generated by Django 5.2.17 on 2026-10-07 07:46

import api.storage
import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_backfill_search_and_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcountline',
            name='quantity_at_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='الرصيد عند العدّ'),
        ),
        migrations.AddField(
            model_name='supplydeal',
            name='previous_cost_currency',
            field=models.CharField(blank=True, default='', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='supplydeal',
            name='previous_foreign_cost',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, storage=api.storage.private_storage, upload_to='payment_proofs/', validators=[api.validators.validate_image_upload], verbose_name='صورة الإشعار'),
        ),
    ]
