# Generated by Django 5.2.17 on 2026-10-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_review_fixes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(default='اسبير', max_length=255, verbose_name='اسم الموقع'),
        ),
    ]
