# Generated by Django 5.2.17 on 2026-10-08 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_refresh_search_and_reference_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicorder',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='public_order', to='api.invoice', verbose_name='فاتورة البيع'),
        ),
        migrations.AlterField(
            model_name='publicorder',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'تم التأكيد'), ('completed', 'تم البيع'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('sale', 'بيع'), ('public_order_confirmed', 'تأكيد طلب خارجي'), ('public_order_cancelled', 'إلغاء طلب خارجي'), ('public_order_invoiced', 'تحرير حجز طلب خارجي لبيعه بفاتورة'), ('restock', 'توريد'), ('restock_reversal', 'إلغاء توريد'), ('return', 'مرتجع'), ('adjustment', 'تسوية يدوية'), ('opening', 'رصيد افتتاحي'), ('stock_count', 'جرد')], max_length=32, verbose_name='السبب'),
        ),
    ]
