# Generated by Django 5.2.17 on 2026-10-09 20:02

from django.db import migrations, models

OLD_DEFAULT = 'نوفر أفضل قطع الغيار الأصلية والمضمونة لكافة أنواع السيارات بأسعار منافسة.'
NEW_DEFAULT = 'نوفر قطع غيار لكافة أنواع السيارات بدرجات جودة واضحة — أصلي وتجاري ومستعمل — وبأسعار منافسة.'


def neutral_subtitle(apps, schema_editor):
    """
    النص الافتراضي القديم يعد كل الزبائن بقطع «أصلية ومضمونة» حتى لمحل يبيع
    المستعمل والتجاري. يُستبدل فقط حيث لم يغيّره صاحب المحل.
    """
    apps.get_model('api', 'SiteSetting').objects.filter(hero_subtitle=OLD_DEFAULT).update(
        hero_subtitle=NEW_DEFAULT,
    )


def restore_subtitle(apps, schema_editor):
    apps.get_model('api', 'SiteSetting').objects.filter(hero_subtitle=NEW_DEFAULT).update(
        hero_subtitle=OLD_DEFAULT,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_public_order_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_subtitle',
            field=models.TextField(default='نوفر قطع غيار لكافة أنواع السيارات بدرجات جودة واضحة — أصلي وتجاري ومستعمل — وبأسعار منافسة.', verbose_name='العنوان الفرعي للهيرو'),
        ),
        migrations.RunPython(neutral_subtitle, restore_subtitle),
    ]
